### PR TITLE
add an icon in SVG format

### LINKED ISSUE #185: icon available in SVG format (or resized to reasonable dimensions)
Hi,

I am currently packaging dsda-doom to replace prboom-plus in Debian, and in the course of this I found that dsda-doom lacks an icon in SVG format and only ships one in PNG format with very odd 2002x2104 dimensions. Would it be possible to add an icon in SVG format?

 - Fabian
 -

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Created from the PNG format icon, resized to 512x512, using png2svg and svgo.

Fixes #185

### CODE REVIEW

**Comment by kraflab** [comment]
You can't just convert a png to svg and obtain the benefits of svg. This is based on a reduced resolution compared to the source in the repo, so the quality even at that level is reduced. This would basically be a regression and to me does not serve much purpose.

Existing fidelity:
Screenshot_20230418_125605_Firefox

svg:
Screenshot_20230418_125636_Firefox

**Comment by fabiangreffrath** [comment]
Ouch! Didn't zoom it in that far. 😮

**Comment by bkoropoff** [comment]
Here's a quick-and-dirty image trace with Inkscape you can use as a base.  It needs some fine-grained cleanup and some areas filled with white, etc.

dsda-doom

The original appears to be vector art, so it would be easier to just ask the original artist for an svg.

**Comment by kraflab** [comment]
The original artist said it's not possible to create an svg easily from the original source.

**Comment by bkoropoff** [comment]
Hmm, ok.  Cleaned it up a bit more.
dsda-doom-plain

**Comment by fabiangreffrath** [comment]
Erm, wow!

**Comment by kraflab** [comment]
That looks reasonable to me

**Comment by bkoropoff** [comment]
[Inkscape did most of the heavy lifting](https://inkscape-manuals.readthedocs.io/en/latest/tracing-an-image.html), it just needed some manual touch-ups.

**Comment by kraflab** [comment]
@fabiangreffrath do you want to add bkoropoff's svg?

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath do you want to add bkoropoff's svg?

Yes, I'll update my PR.

**Comment by kraflab** [comment]
Thanks 👍

**Pull request merged**
