### PR TITLE
Timer compile fix for MSVC

### PR DESCRIPTION
**Pull request by XaserAcheron**
Can't guarantee this is all kosher, but it was enough to get me up and running, so here's the PR. :P

### CODE REVIEW

**Comment by kraflab** [comment]
Is `struct timespec` already defined?

**Comment by XaserAcheron** [comment]
Ye, it seems to be -- compiler went "hey yo this already exists" on that line so I took it out and it worked. ;)

[EDIT] It's in Microsoft's version of `<time.h>`

**Comment by kraflab** [comment]
The only remaining concern is "does it work" but since the official builds aren't made this way and you made it clear in the comment, better to have something that can compile for devs in this environment in the short term at least.

**Comment by XaserAcheron** [comment]
Heh, yeah, this is definitely "swim at your own risk" territory, IMO.

**Pull request merged**
