### PR TITLE
gl_sky: don't smash vbo id on reinit

### PR DESCRIPTION
**Pull request by bkoropoff**
Probable fix for #325

### CODE REVIEW

**Comment by bkoropoff** [comment]
cc @kraflab

**Comment by kraflab** [comment]
See the issue for an update on how to reproduce it. This still crashes for me.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/099b3aaa5c1ca3f9c8f814effb0e3ecac0f1a27a

**Comment by bkoropoff** [comment]
@kraflab This didn't fix the bug, but I think it's a legitimate (different) bug.  The code as-is will leak GPU buffers.

**Pull request merged**
