### PR TITLE
Remove old shader mode

### PR DESCRIPTION
**Pull request by kraflab**
There were a lot of logical collapses in the gl code base when resolving everything to indexed light mode. Hi res and detail textures have disappeared, and various globals are no longer needed. There is no longer a "light mode" concept because there is only one opengl rendering style now.

### CODE REVIEW

**Comment by andrey-budko** [comment]
dsda-doom.exe hg.wad
```
---------------------------
dsda-doom
---------------------------
createPatch: Unknown patch format STBAR.
---------------------------
ОК   
---------------------------
```

dsda-doom.exe vg.wad
```
---------------------------
dsda-doom
---------------------------
createPatch: Unknown patch format STKEYS0.
---------------------------
ОК   
---------------------------
```

**Comment by kraflab** [comment]
I'm aware this costs support for a few wads, but I decided the benefits outweigh the costs. I'm interested in eventually coming up with a strategy to support these things in indexed mode somehow, but not yet.

**Comment by kraflab** [comment]
Ah but it should detect the working patches. I guess we need to catch and disregard the hi res ones.

**Comment by andrey-budko** [comment]
But it should not exit, right? There are "good" (no hires) STBAR and STKEYS0 lumps there.

**Comment by kraflab** [comment]
Yes, thanks for the catch, this does need to be fixed. I had tested frozen time which loaded fine, but didn't check these.

**Comment by andrey-budko** [comment]
Do we just need to restore this line?
`W_CoalesceMarkedResource("HI_START", "HI_END", ns_hires);`

**Comment by kraflab** [comment]
Does that hide the lumps away when not using that namespace?

**Comment by andrey-budko** [comment]
I think hires lumps are ns_global now, but they should not because of
```cpp

W_FindNumFromName(const char *name, int lump)
        { return W_FindNumFromName2(name, ns_global, lump); }

W_CheckNumForName(const char *name)
        { return W_CheckNumForName2(name, ns_global); }
```

**Comment by kraflab** [comment]
Alright, should be a quick fix then, thanks for investigating 🤠

**Pull request merged**
