### PR TITLE
Fix skydome seam

### LINKED ISSUE #329: Thin seam on skydome
After replacing float with double here https://github.com/kraflab/dsda-doom/commit/e38c040e9480ffd36050da05f3a35e2d991cae2a

image

### PR DESCRIPTION
**Pull request by andrey-budko**
Closes #329

### CODE REVIEW

**Comment by kraflab** [comment]
Thanks!

**Comment by andrey-budko** [comment]
Now I'm not sure about the speed of all these sin/cos.

Is this enough?
```diff
- angle_t topAngle = (angle_t)(c / (double)columns * ANGLE_MAX);
+ angle_t topAngle = (angle_t)((c == columns ? 0 : c) / (double)columns * ANGLE_MAX);
```

**Comment by kraflab** [comment]
You mean to revert everything and just add that diff?

**Comment by andrey-budko** [comment]
`finesine` for the first point (0 rad) and for the last (2pi rad) do not match with 'double' version - and probably that's the problem.

https://godbolt.org/z/qWbeYn6Ye

GZDoom uses precise sin/cos version though.
https://github.com/ZDoom/gzdoom/blob/master/src/common/rendering/hwrenderer/data/hw_skydome.cpp#L148

Do we care about speed in that place?

**Pull request merged**
