### PR TITLE
gl_preprocess: revert out self-ref sector hacks

### PR DESCRIPTION
**Pull request by bkoropoff**
I think it's going to take a more radical approach to fix self-referencing sectors.  Putting things back the way they were while I do some experimenting.

### CODE REVIEW

**Comment by kraflab** [comment]
So this undoes the self referencing improvements, but the bleed fixes are still there right? So av01 is broken again but kdikdizd is still fixed? Just making sure I know where this puts us 😄

**Comment by kraflab** [comment]
I thought this code was still an improvement, and didn't introduce any new bugs. Is that not the case? Just thinking if that's true it doesn't need to be reverted on master until something else is ready.

**Comment by bkoropoff** [comment]
Yeah, the bleeding fixes seem fine.  The current self-ref detection code is conceptually broken (e.g. the test for a line being interior or exterior is obviously wrong in retrospect).  I'm not sure when you're planning to do another release, so I didn't want to leave known-incorrect code in master.

**Comment by kraflab** [comment]
Alright then, let's clean it up for the time being.

**Pull request merged**
