### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by jengelh**

### CODE REVIEW

**Comment by kraflab** [comment]
The .gitignore already covers multiple file structure options. If you don't like what's there you can make a local .gitignore to cover the difference, but I don't think we need to keep adding more to this file.

**Comment by jengelh** [comment]
>The .gitignore already covers multiple file structure options

Whatever it already has is not enough to cover cmake artifacts. And cmake is the build system you prescribe with dsda-doom… so please.

**Comment by Pedro-Beirao** [comment]
cmake and make should be ran inside a build folder, not from /prboom2
That's why build/* is in the .gitignore

**Comment by kraflab** [comment]
Closing in favor of the linked PR.

**Pull request closed without merging**
