### PR TITLE
Fix red translucent sprites in indexed lightmode

### PR DESCRIPTION
**Pull request by rrPKrr**

### CODE REVIEW

**Comment by kraflab** [comment]
This fixes the sprites but not the fact that fuzz is drawn on top of the pain screen, is that right?

**Comment by rrPKrr** [comment]
Yes, that's right.

**Comment by jackrjli** [comment]
This also fixes an issue I saw with translucent textures in Bauhaus MAP01:
doom00

**Comment by kraflab** [comment]
Thanks 😸

**Comment by kraflab** [comment]
@XaserAcheron FYI - depending on how the fuzz is fixed later on, we may want to revert this

**Pull request merged**
