### PR TITLE
Fix some minor memory leaks

### PR DESCRIPTION
**Pull request by bkoropoff**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
@rfomin Does this affect our implementation as well?

**Comment by kraflab** [comment]
👍

**Comment by rfomin** [comment]
> @rfomin Does this affect our implementation as well?

Yes, fixed.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/4386bddb071db6dbbf06632531f907808035b0a5 fyi (not sure this affects woof, but in dsda-doom these arrays are not guaranteed to be populated - for instance in heretic).

**Comment by fabiangreffrath** [comment]
Thanks, but in Woof these arrays are always allocated. Right @rfomin ?

**Comment by rfomin** [comment]
> Thanks, but in Woof these arrays are always allocated. Right @rfomin ?

Yes, I think we're all right.

**Pull request merged**
